vt:
  path: "vt"
  name: "Route Graphics UI Visual Tests"
  description: "Visual testing for Route Graphics"
  sections:
    - title: "Text"
      type: "groupLabel"
      items:
        - title: "Text Basic"
          files: "textbasic"
          description: "Basic text rendering tests"
