vt:
  path: "vt"
  name: "Route Graphics UI Visual Tests"
  description: "Visual testing for Route Graphics"
  sections:
    - title: "Container"
      type: "groupLabel"
      items:
        - title: "Container"
          files: "container"
          description: "Container layout and positioning tests"
    - title: "Rect"
      type: "groupLabel"
      items:
        - title: "Rect"
          files: "rect"
          description: "Rect primitive rendering tests"
        - title: "Rect Transitions"
          files: "recttransition"
          description: "Rect transitions and animations tests"
    - title: "Sprite"
      type: "groupLabel"
      items:
        - title: "Sprite Basic"
          files: "spritebasic"
          description: "Basic sprite rendering and positioning tests"
        - title: "Sprite Transitions"
          files: "spritetransition"
          description: "Sprite animation and transition tests"
        - title: "Sprite Updates"
          files: "spriteupdate"
          description: "Sprite property update tests"
    - title: "Text"
      type: "groupLabel"
      items:
        - title: "Text Basic"
          files: "textbasic"
          description: "Basic text rendering tests"
        - title: "Text Revealing"
          files: "textrevealing"
          description: "Text revealing animation tests"
    - title: "Audio"
      type: "groupLabel"
      items:
        - title: "Audio Basic"
          files: "audio"
          description: "Audio sound playback tests"
    - title: "Global"
      type: "groupLabel"
      items:
        - title: "Global Configuration"
          files: "global"
          description: "Global configuration tests including cursor styles"
