vt:
  path: "vt"
  name: "Route Graphics UI Visual Tests"
  description: "Visual testing for Route Graphics"
  sections:
    - title: "Text"
      type: "groupLabel"
      items:
        - title: "Text Basic"
          files: "textbasic"
          description: "Basic text rendering tests"
    - title: "Container"
      type: "groupLabel"
      items:
        - title: "Container"
          files: "container"
          description: "Container rendering test"
    - title: "Rect"
      type: "groupLabel"
      items:
        - title: "Rect"
          files: "rect"
          description: "Rect rendering test"
    - title: "Sprite"
      type: "groupLabel"
      items:
        - title: "Sprite"
          files: "sprite"
          description: "Sprite rendering test"
