name: Publish package route-graphics to npm
on:
  push:
    tags:
      - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.5

      # Install dependencies from root
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Check package contents and CLI entry points
        run: bun run test:package

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      # Publish to npm
      - name: Publish to npm (Trusted)
        run: npm publish --access public
